RSDK-3052, RSDK-3053, RSDK-3417 Create Intel RealSense C++ Module
viamrobotics/viam-camera-realsense pull request #2
Opened 2023-07-03 17:12 UTC by bhaney

This is a modularization of the C++ server originally from github.com/viamrobotics/camera-servers

Manual tests show that it has the same speed/FPS as the remote server,
i.e. at 640 x 480 resolution, it performs
23 FPS for depth using image/vnd.viam.dep
60 FPS for color using image/jpeg

It also has the option to allow the setting of the endian-ness of the raw depth data in its config.

Two other features for future PRs are:

- the addition of the get_images method to return both color and depth at the same time.
- the get_pointclouds method to allow returning a PCD.

2023-07-03 18:27 UTC, bhaney commented on camera_realsense.cpp
> +    vsdk::Camera::point_cloud get_point_cloud(std::string mime_type) override {
this method will be implemented in a future PR

2023-07-03 18:27 UTC, bhaney commented on camera_realsense.cpp
> +    void on_device_reconnect(rs2::event_information& info, rs2::pipeline pipeline) {
This callback method does not seem to work on modules, created a ticket
https://viam.atlassian.net/browse/RSDK-3884

2023-07-06 17:17 UTC, bhaney commented on camera_realsense.cpp
> +    void reconfigure(vsdk::Dependencies deps, vsdk::ResourceConfig cfg) override {
@stuqdog A question for you on module reconfiguration in C++: the expected behavior here is that only the background pipeline that pulls from the Intel RealSense gets restarted with the new configuration parameters, and not the entire module. Is that the case when reconfiguration happens?

2023-07-07 17:39 UTC, bhaney commented on camera_realsense.cpp
> +    void on_device_reconnect(rs2::event_information& info, rs2::pipeline pipeline) {
JK! Was a bug on my part

2023-07-07 19:08 UTC, stuqdog commented on camera_realsense.cpp
> +    void reconfigure(vsdk::Dependencies deps, vsdk::ResourceConfig cfg) override {
Yes, provided a `reconfigure` method exists it will execute without any broader impact on the module.

2023-07-07 19:19 UTC, bhaney commented on camera_realsense.cpp
> +void on_device_reconnect(rs2::event_information& info, rs2::pipeline pipeline,
I declare the function prototype here because of func circular dependency between `frameLoop` and `on_device_reconnect`. It works, but it makes me uncomfortable, as I will explain below.

`on_device_reconnect` is a callback function that stops and restarts `frameLoop` if the intel RealSense gets disconnected for any reason. But, in order for that callback function to always be listening, the `rs2::context` variable that holds the callback function shouldn't get destroyed/go out of scope. So what happens is--

1. frameLoop is called when the module first gets constructed, and placed into a separate thread.
2. frameLoop intializes a rs::context, which holds the `on_device_reconnect` function in it for the lifetime of the frameLoop (which is in an infinite loop).
3. If the intel realsense device gets disconnected/reconnected, the callback function `on_device_reconnect` gets triggered. It uses the condition_variable and various shared bools to break out the infinite loop of the frameLoop function, and lets it exit (thus making the rs::context go out of scope? this is the part that I thought would cause problems...)
4. Even though `frameLoop` is no more, and the original rs::context is out of scope, `on_device_reconnect` is still running! It then sets up a NEW `frameLoop`, which sets up a NEW rs::context, which sets up a NEW callback function for `on_device_reconnect`
5. This all works! It's snappy too!

2023-07-07 19:25 UTC, bhaney commented on camera_realsense.cpp
> +        }
There are two scenarios in which the `frameLoop` needs to be stopped and restarted. 
1. Reconfiguration
2. Device re-connection

This is the device re-connection scenario. shouldRun is set to false, which allows `frameLoop` to exit. before exiting, `frameLoop` sets isRunning to false. Once this function sees that `frameLoop` has exited, it uses the old config that is stored in the module to restart the intel realsense device and also create a new `frameLoop`.

2023-07-07 19:26 UTC, bhaney commented on camera_realsense.cpp
> +        }
There are two scenarios in which the `frameLoop` needs to be stopped and restarted. 
1. Reconfiguration
2. Device re-connection

This is the re-intialization scenario. shouldRun is set to false, which allows `frameLoop` to exit. Before exiting, `frameLoop` sets isRunning to false. Once initialize sees that `frameLoop` has exited, it uses the new ResourceConfig to restart the intel realsense device and also create a new `frameLoop` with all the new settings.

2023-07-10 14:25 UTC, stuqdog requested changes
I can't really speak to much of the camera logic but some general structural comments, mostly pretty minor.

2023-07-10 14:25 UTC, stuqdog commented on camera_realsense.cpp
> +        return 0;
does this compile correctly? I'd expect that returning an `int` here would create issues given the function signature. Might make sense to just throw an unimplemented error?

2023-07-11 15:16 UTC, bhaney commented on camera_realsense.cpp
> +#include <arpa/inet.h>
People are hopefully just going to download a binary and never have to work with or incorporate the source code into their own stuff.

2023-07-11 15:18 UTC, bhaney commented on camera_realsense.cpp
> +tuple<vector<uint8_t>, bool> encodeColorPNG(const uint8_t* data, const int width,
creating structs for all of the returned tuples seems like a good way of "self-documenting" things, so I'll def do that!

2023-07-12 20:06 UTC, acmorrow reviewed
Overall, this looks good. I think it would be much easier to review though if it could be redone in a way that made the PR a delta above the old grpc server, because then it would be much much easier to know where to spend time reviewing, and where to just accept that the old logic was "good enough" for a v1. I think it might not be that hard to do.

2023-07-12 20:06 UTC, acmorrow commented on camera_realsense.cpp
> +        GLOBAL_LATEST_FRAMES.mutex.lock();
Yes, raw calls to `lock` should definitely be avoided.

2023-07-12 20:06 UTC, acmorrow commented on camera_realsense.cpp
> +        return 0;
`AttributeMap` is a shared_ptr, so this is equivalent to returning nullptr.

2023-07-12 20:07 UTC, acmorrow commented
> Overall, this looks good. I think it would be much easier to review though if it could be redone in a way that made the PR a delta above the old grpc server, because then it would be much much easier to know where to spend time reviewing, and where to just accept that the old logic was "good enough" for a v1. I think it might not be that hard to do.

Well, I sort of got tunnel vision on the C++ part and forgot to take a closer look at the supporting context. Let me take a quick look through that now

2023-07-12 20:15 UTC, acmorrow commented on etc/Dockerfile.debian.bookworm
> +RUN cp -r ${HOME}/opt/src/viam-cpp-sdk/build/install/* /usr/local/
You should instead just build the viam-cpp-sdk with `/usr/local` as the install prefix.

2023-07-12 20:15 UTC, acmorrow commented on Makefile
> +   GCC_FLAGS += -mpclmul -msse2 -msse4.2
May be subsumed by the gcc flag `-march=westmere` which implies all of these flags.

2023-07-12 20:15 UTC, acmorrow commented on Makefile
> +   GCC_FLAGS += -mpclmul -msse2 -msse4.2
So, librealsense seems to have cmake `find_package` support. I think it is worth considering whether you want to eventually write a CMake infra for this module.

2023-07-12 20:26 UTC, bhaney commented on camera_realsense.cpp
> +tuple<vector<uint8_t>, bool> encodeColorPNG(const uint8_t* data, const int width,
done

2023-07-12 20:27 UTC, bhaney commented on camera_realsense.cpp
> +using namespace std;
removed all the `using` keywords

2023-07-12 20:27 UTC, bhaney commented on camera_realsense.cpp
> +using namespace viam::sdk;
done

2023-07-12 20:31 UTC, edaniels commented on camera_realsense.cpp
> +    const auto& [encoded, ok] = encodeColorPNG(data, width, height);
I would never!

2023-07-12 20:32 UTC, edaniels commented on camera_realsense.cpp
> +    const auto& [encoded, ok] = encodeColorPNG(data, width, height);
but yeah optional is totally better anyway

2023-07-12 21:05 UTC, bhaney commented on camera_realsense.cpp
> +void on_device_reconnect(rs2::event_information& info, rs2::pipeline pipeline,
the previous code doesn't have the circularity issue because the `startPipeline` and `rs2::context` are called in the `main` function, which is always alive as long as the process is alive. Since a module needs to start before the actual component needs to start, the pipeline no longer gets spun up right when main begin.

2023-07-13 14:29 UTC, acmorrow commented on camera_realsense.cpp
> +using namespace std;
> Does this matter in the context of this being a binary, not a library?

No, it doesn't really matter binary vs library. You aren't actually importing more/less by saying it. But there are a lot of names in `std` and it is an ever increasing set. Saying `using namespace std` just introduces fragility w.r.t. future collisions between the standard library and all the other code (in use) here.

2023-07-19 20:51 UTC, bhaney commented on Makefile
> +   GCC_FLAGS += -mpclmul -msse2 -msse4.2
I will make a ticket for this

2023-07-19 20:54 UTC, bhaney commented on Makefile
> +   GCC_FLAGS += -mpclmul -msse2 -msse4.2
https://viam.atlassian.net/browse/RSDK-4097

2023-07-19 21:40 UTC, bhaney commented on camera_realsense.cpp
> +    return response;
since I have now created a struct to hold the response `jpeg_image`, do I still need to call delete on the pointer? Or when the struct goes out of scope, does it get destroyed automatically?

2023-07-20 22:11 UTC, bhaney commented on camera_realsense.cpp
> +    return response;
using unique_ptr's now to take care of the memory

2023-07-20 22:12 UTC, bhaney commented on camera_realsense.cpp
> +#define RESOURCE_TYPE "CameraRealSense"
done

2023-07-20 22:12 UTC, bhaney commented on camera_realsense.cpp
> +    ((1 == htonl(1)) ? (x) : ((uint64_t)htonl((x)&0xFFFFFFFF) << 32) | htonl((x) >> 32))
done

2023-07-20 22:12 UTC, bhaney commented on camera_realsense.cpp
> +
done

2023-07-20 22:13 UTC, bhaney commented on camera_realsense.cpp
> +bool DEBUG = false;
done

2023-07-20 22:13 UTC, bhaney commented on camera_realsense.cpp
> +std::vector<unsigned char> convertToVector(const unsigned char* data, size_t size) {
deleted the function

2023-07-20 22:13 UTC, bhaney commented on camera_realsense.cpp
> +    return std::vector<unsigned char>(begin, end);
deleted the function

2023-07-20 22:14 UTC, bhaney commented on camera_realsense.cpp
> +            // NOTE(erd): this is fast enough in -O3 (1920x1080 -> ~15ms) but could probably be
remove the comment

2023-07-24 18:28 UTC, stuqdog approved these changes
One small fix required (no need to re-request review) otherwise lgtm!

2023-07-24 18:28 UTC, stuqdog commented on camera_realsense.cpp
> +        GLOBAL_LATEST_FRAMES.mutex.lock();
here (and below) we should create a `std::lock_guard(...)` rather than assuming responsibility for unlocking ourselves.

Also just to confirm, should we still have the comment from Eric above?

2023-07-24 18:41 UTC, acmorrow commented on camera_realsense.cpp
> -void frameLoop(rs2::pipeline pipeline, AtomicFrameSet& frameSet, promise<void>& ready,
Could frameLoop be moved back down to its original location? I think it would make the review a lot easier. If there is a declaration order circularity, it can be broken by writing prototypes for the functions involved in the cycle up at the top of the unnamed namespace.

2023-07-24 18:41 UTC, acmorrow commented on camera_realsense.cpp
> +std::tuple<rs2::pipeline, RealSenseProperties> startPipeline(bool disableDepth, int depthWidth,
Any particular reason for destructuring away `DeviceProperties`?

2023-07-24 18:41 UTC, acmorrow commented on camera_realsense.cpp
> +void on_device_reconnect(rs2::event_information& info, rs2::pipeline pipeline,
I think it will be easier to see the effects of these changes if you restore the original order of function implementations with `frameLoop` and `on_device_reconnect` and break the calling circularity by declaring prototypes for those functions top-of-scope.

2023-07-24 18:41 UTC, acmorrow commented on camera_realsense.cpp
> +    auto fillProps = [](auto intrinsics, std::string distortionModel) -> CameraProperties {
Below, `camProps.distortionModel = std::move(distortionModel)`, or, have this lambda take `distortionModel` by `const&`. As written there are two copies and you only need one. Given that it appears to be called in at least one place with a string literal, I'd opt for the `std::move` below.

2023-07-24 18:41 UTC, acmorrow commented on camera_realsense.cpp
> +        if (this->device_ != nullptr) {
style nit, but I'd write this like:
```
if (!this->device_)
    return;

std::unique_lock<std::mutex> ...
```

2023-07-24 18:41 UTC, acmorrow commented on camera_realsense.cpp
> +        return *response;
I think, but am not confident, that you want `return std::move(*response)` here. Can you try building with `-Wpessimizing-move` and `-Wredundant-move` to make sure that it 1) isn't harmful and 2) isn't redundant?

2023-07-24 18:41 UTC, acmorrow commented on camera_realsense.cpp
> +                response.images.push_back(*color_response);
Similarly, I suspect you want a `std::move` here and a call to `std::vector::emplace_back`.

2023-07-24 18:41 UTC, acmorrow commented on camera_realsense.cpp
> +                response.images.push_back(*depth_response);
Here too.

2023-07-24 18:47 UTC, acmorrow commented
@bhaney - I left a bunch of comments, but I'd classify almost all of them as optional improvements to take or leave as you see fit. I would however like to see `frameLoop` and `on_device_reconnect` restored to their original sequencing in the file so that I can see what really changed there. I think you can resolve any circularity by just writing prototypes for the functions at issue at the beginning of the unnamed namespace. If you can do that I think I can take a quick final look and then approve this, and you can act or not on my suggestions.

2023-07-24 21:46 UTC, bhaney commented on camera_realsense.cpp
> +        GLOBAL_LATEST_FRAMES.mutex.lock();
oops, sorry for missing your previous comment! Yes I will fix this

2023-07-25 16:37 UTC, bhaney commented on camera_realsense.cpp
> +    std::shared_ptr<std::vector<uint16_t>> depthFrame;
So, my justification here is that the GLOBAL_FRAME_SET is a shared memory object that pull raw info from the intel realsense, and stores it until the gRPC server gets a request. So, if many clients are requesting the image, then the server may be serving the same image to multiple clients. I was thinking - I don't want to copy the pointer data in the pointer until i really have to. So if one client is requesting "turn this raw data into a PNG" and the other is "turn this raw data into a JPEG" I'd want both of the functions to be able to read from the same raw data memory, rather than first having to copy the raw data into their respective functions, and then transforming the raw data into a PNG/JPEG.

This may be a completely wrong model of how memory works, in which case, I really would like a correction and to know what would be happening under the hood!

2023-07-25 17:33 UTC, bhaney commented on camera_realsense.cpp
> +};
done

2023-07-25 17:34 UTC, bhaney commented on camera_realsense.cpp
> +    response->bytes = encoded.color_bytes;
done

2023-07-25 17:41 UTC, acmorrow commented on camera_realsense.cpp
> +    std::shared_ptr<std::vector<uint16_t>> depthFrame;
Not wrong at all, it makes total sense, it just wasn't obvious what was going on just by seeing the declaration. There are some ways you could make that intent clearer and make it "correct by construction" by using a class, but I don't think this is the time to pursue that. I wondered for a moment how that strategy could also be working for `colorFrame`, but it appears that it has handle like semantics to a refcounted underlying, so it seems the same strategy works there too. I'll resolve this thread.

2023-07-25 17:46 UTC, bhaney commented on camera_realsense.cpp
> +    bool ok;
changed to optional

2023-07-25 17:50 UTC, bhaney commented on camera_realsense.cpp
> +    bool ok;
done

2023-07-25 17:51 UTC, bhaney commented on camera_realsense.cpp
> +        std::cerr << "[GetImage]  failed to init JPEG compressor" << std::endl;
this I'm not sure about- JPEG though is super fast. even on a RPi it runs at 80FPS

2023-07-25 20:48 UTC, bhaney commented on camera_realsense.cpp
> -void frameLoop(rs2::pipeline pipeline, AtomicFrameSet& frameSet, promise<void>& ready,
Yes, moved frame loop and the other functions back to their original locations

2023-07-25 21:15 UTC, bhaney commented on camera_realsense.cpp
> +        return {std::move(uniqueEncoded), encodedSize, false};
will instead return std::nullopt

2023-07-25 21:15 UTC, bhaney commented on camera_realsense.cpp
> +        std::cerr << "[GetImage]  failed to init JPEG compressor" << std::endl;
I think for this round, I'll skip this

2023-07-25 21:18 UTC, bhaney commented on camera_realsense.cpp
>      tjCompress2(handle, data, width, 0, height, TJPF_RGB, &encoded, &encodedSize, TJSAMP_420, 75,
added a check for the return int

2023-07-25 21:23 UTC, bhaney commented on camera_realsense.cpp
> +};
trying it out

2023-07-25 21:35 UTC, bhaney commented on camera_realsense.cpp
> +    std::unique_ptr<unsigned char> uniqueEncoded(encoded);
I think I got it - made a constructor for jpeg_image.

2023-07-25 21:37 UTC, bhaney commented on camera_realsense.cpp
> +    response->bytes = std::move(
yea, I think for jpeg specifically, the optimization is not important, but I did switch to using assign

2023-07-25 21:41 UTC, bhaney commented on camera_realsense.cpp
> +    std::unique_ptr<unsigned char[]> uniqueBuf(rawBuf);
I think I will just change the rawBuf defintion to `std::unique_ptr<unsigned char[]> rawBuf(new unsigned char[totalByteCount]);`

2023-07-25 21:42 UTC, bhaney commented on camera_realsense.cpp
> +    response->bytes = std::move(
done

2023-07-25 21:44 UTC, bhaney commented on camera_realsense.cpp
> +    std::unique_ptr<unsigned char[]> uniqueBuf(rawBuf);
yes, changing the definition of rawBuf to just be the unique_ptr

2023-07-25 21:49 UTC, bhaney commented on camera_realsense.cpp
> +    response->bytes = std::move(
done - I think eliminating the extra copy will be an optimization we will do only if we really need to. So we'll skip it for now

2023-07-25 21:49 UTC, bhaney commented on camera_realsense.cpp
> +    std::unique_ptr<unsigned char[]> uniqueBuf(rawBuf);
done

2023-07-25 21:49 UTC, bhaney commented on camera_realsense.cpp
> +    response->bytes = std::move(
done

2023-07-25 21:54 UTC, bhaney commented on camera_realsense.cpp
> +std::tuple<rs2::pipeline, RealSenseProperties> startPipeline(bool disableDepth, int depthWidth,
DeviceProperties has become this unique struct that holds the mutexes, condition_variables, and bools that represent whether a device is running or not, and how to stop and restart things when things get reconfigured and such... 

startPipeline just needs the parameters that will determine the image size of the images when the device starts running. I wanted to sequester it away from the frameLoop and reconfigure functions a bit -- it was easier to think about how that function worked when I realized I didn't have to worry about it controlling the stopping or restarting of anything.

2023-07-25 21:58 UTC, bhaney commented on camera_realsense.cpp
> +    auto fillProps = [](auto intrinsics, std::string distortionModel) -> CameraProperties {
done

2023-07-25 22:01 UTC, bhaney commented on camera_realsense.cpp
> +        if (this->device_ != nullptr) {
done

2023-07-25 22:03 UTC, bhaney commented on camera_realsense.cpp
> +                response.images.push_back(*color_response);
nice! this is awesome

2023-07-25 22:03 UTC, bhaney commented on camera_realsense.cpp
> +                response.images.push_back(*depth_response);
thanks!

2023-07-25 22:17 UTC, bhaney commented on etc/Dockerfile.debian.bookworm
> +    cmake  -DVIAMCPPSDK_USE_DYNAMIC_PROTOS=ON -DVIAMCPPSDK_OFFLINE_PROTO_GENERATION=ON -DCMAKE_INSTALL_PREFIX=/usr/local .. -G Ninja  && \
done

2023-07-25 22:17 UTC, bhaney commented on etc/Dockerfile.debian.bookworm
> +    cmake .. -DBUILD_EXAMPLES=false -DBUILD_GRAPHICAL_EXAMPLES=false -DCMAKE_BUILD_TYPE=Release  && \
done

2023-07-25 22:20 UTC, bhaney commented on camera_realsense.cpp
> +        return *response;
oh nice! adding these flags didn't produce any extra warnings

2023-07-25 22:29 UTC, bhaney commented on camera_realsense.cpp
> +    std::unique_ptr<unsigned char[]> uniqueEncoded(encoded);
so far I haven't gotten any warnings or anything from the compiler at least - should I go back to handling the memory like before, and manually free it?

2023-07-25 22:33 UTC, bhaney commented on etc/Dockerfile.debian.bookworm
> +RUN apt-add-repository -y 'deb http://apt.llvm.org/bookworm/ llvm-toolchain-bookworm-15 main'
removed

2023-07-25 22:33 UTC, bhaney commented on camera_realsense.cpp
> +        GLOBAL_LATEST_FRAMES.mutex.lock();
done

2023-07-25 22:55 UTC, bhaney commented on camera_realsense.cpp
> -    }
This stuff that was removed from the main() function is now all in the initialize function within the class.

2023-07-25 23:19 UTC, bazile-clyde requested changes

2023-07-25 23:19 UTC, bazile-clyde commented on camera_realsense.cpp
> +    std::cout << "About to servce on socket " << argv[1] << std::endl;
`servce` typo?

2023-07-26 15:36 UTC, bhaney commented on README.md
> +        "enable_point_clouds": false
You actually get an "unimplemented" error both ways now. Probably best to just remove it from the README for now

2023-07-26 15:36 UTC, bhaney commented on camera_realsense.cpp
>      htonl(1380401729);  // the utf-8 binary encoding for "RGBA", big-endian
It would be our RDK source code. That's where we define this Viam standard

2023-07-26 15:38 UTC, bhaney commented on camera_realsense.cpp
>      tjDestroy(handle);
yeah, the handle should always be destroyed. try/finally makes sense

2023-07-26 15:39 UTC, bhaney commented on camera_realsense.cpp
> +constexpr char service_name[] = "camera_realsense";
the service name is a required argument in the module constructor - I'm not entirely sure how the module uses it though?

And Andrew pointed out that constexpr was the alternative to using #define statements in more modern C++

2023-07-26 15:40 UTC, bhaney commented on camera_realsense.cpp
> +    std::cout << "About to servce on socket " << argv[1] << std::endl;
good catch!

2023-07-26 15:42 UTC, bhaney commented on camera_realsense.cpp
> +                                                                  const uint height) {
I'll add a non-negative requirement to the validate function, so that user's can't input a negative number from the config, so that assertions will happen at the config phase

2023-07-26 15:54 UTC, bhaney commented on camera_realsense.cpp
> +constexpr char service_name[] = "camera_realsense";
ah, I ended up using `kResourceType` in the constructor - I can get rid of service_name! Good catch

2023-07-26 15:59 UTC, bhaney commented on camera_realsense.cpp
> +        auto start = std::chrono::high_resolution_clock::now();
yes - changing everyhing to use
```
    std::chrono::time_point<std::chrono::high_resolution_clock> start;
     if (debug_enabled) {
        start = std::chrono::high_resolution_clock::now();
    }
```

2023-07-26 16:10 UTC, bhaney commented on camera_realsense.cpp
>      tjDestroy(handle);
looks like C++ doesn't have try-finally, but I can put the destroy in the catch block, as well as outside of it

2023-07-26 17:01 UTC, bhaney commented on camera_realsense.cpp
> +        throw std::runtime_error("failed to encode color PNG");
this is a good idea - changed things to just throw errors

2023-07-26 17:04 UTC, bhaney commented on camera_realsense.cpp
>      tjDestroy(handle);
done

2023-07-26 17:05 UTC, bhaney commented on camera_realsense.cpp
> +    if (!encoded.ok) {
getting rid of the OK bool

2023-07-26 19:42 UTC, bhaney commented on camera_realsense.cpp
> +                                                                  const uint height) {
ok changed everything to uint

2023-07-26 20:36 UTC, bhaney commented on camera_realsense.cpp
>      htonl(1380401729);  // the utf-8 binary encoding for "RGBA", big-endian
Or maybe you mean a source that explains that UTF-8 stores all ASCII characters in a single byte, and a table of what the letter's byte encodings are? Maybe if I didn't represent it as decimal and instead used hexadecimal, it would be easier to understand

2023-07-26 20:43 UTC, bhaney commented on camera_realsense.cpp
>      htonl(1380401729);  // the utf-8 binary encoding for "RGBA", big-endian
In binary the number is
R = 01010010 = 0x52
G = 01000111 = 0x47
B = 01000010 = 0x42 
A = 01000001 = 0x41

RGBA =  0x52474241 = 1380401729

2023-07-31 15:59 UTC, bhaney commented on camera_realsense.cpp
> +    std::unique_ptr<unsigned char[]> uniqueEncoded(encoded);
Running for an hour requesting jpegs in a loop didn't produce a memory leak when I did a manual test

2023-07-31 18:27 UTC, acmorrow commented on camera_realsense.cpp
> +    std::unique_ptr<unsigned char[]> uniqueEncoded(encoded);
Well, it is undefined behavior, so even if it doesn't cause problems today, it could in the future. Or ASAN might start reporting the issue at an unexpected (and likely inconvenient) time. In any event, here is an idea about how you could abstract away the correct deletion function so that `encodeDepthPNG` can clean up with `free` and `encodeDepthRAW` can clean up with `operator delete[]`:

```
#include <memory>
#include <iostream>

struct raw_camera_image {
    using deleter_type = void(*)(unsigned char*);
    using uniq = std::unique_ptr<unsigned char[], deleter_type>;

    static constexpr deleter_type free_deleter = [](unsigned char* ptr) {
        std::cout << "Cleaningup with free" << std::endl;
        free(ptr);
    };

    static constexpr deleter_type array_delete_deleter = [](unsigned char* ptr) {
        std::cout << "Cleaning up with operator delete[]" << std::endl;
        delete[] ptr;
    };

    uniq bytes;
    size_t size;
};

raw_camera_image encodeWithMalloc() {
    unsigned char* raw = reinterpret_cast<unsigned char*>(malloc(42));
    raw_camera_image::uniq foo(raw, raw_camera_image::free_deleter);
    return {std::move(foo), 42};
}

raw_camera_image encodeWithOperatorNew() {
    raw_camera_image::uniq foo(new unsigned char[42], raw_camera_image::array_delete_deleter);
    return {std::move(foo), 42};
}

int main() {
    auto rci1 = encodeWithMalloc();
    auto rci2 = encodeWithOperatorNew();
    return 0;
}
```

2023-07-31 18:27 UTC, acmorrow approved these changes
LGTM. I left a comment on how you could pretty easily fix up the mismatched free / delete calls, but I don't think you need to repost it just for that.

2023-08-01 15:28 UTC, bhaney commented on camera_realsense.cpp
> +    std::unique_ptr<unsigned char[]> uniqueEncoded(encoded);
implemented this - thanks!

2023-08-02 02:31 UTC, bazile-clyde reviewed
Looks good. Just a few more comments/questions.

2023-08-02 02:31 UTC, bazile-clyde commented on camera_realsense.cpp
>              for (int i = 0; i < 5; i++) {
Why is this 5? If it's based on the length of `distortionParameters` could the length be used here?

2023-08-02 02:31 UTC, bazile-clyde commented on camera_realsense.cpp
> +        auto response =
Are we returning a shared pointer to an empty map? If so, why? If this is unimplemented, we could throw an error. If we need a dummy value, why not just return a unique pointer, the command argument so it echoes, or just a plain-old empty map?

2023-08-02 02:31 UTC, bazile-clyde commented on camera_realsense.cpp
> +        auto response =
Or you could do what you did for `get_point_cloud`

2023-08-02 14:26 UTC, bhaney commented on camera_realsense.cpp
> +        std::shared_ptr<std::vector<uint16_t>> latestDepthFrame;
So, my justification here is that the GLOBAL_FRAME_SET is a shared memory object that pulls raw info from the intel realsense, and stores it until the gRPC server gets a request. So, if many clients are requesting the image, then the server may be serving the same depth image to multiple clients. I was thinking - I don't want to copy the data the pointer is pointing to until i really have to. So if one client is requesting "turn this raw data into a PNG" and the other is "turn this raw data into a VND.VIAM.DEP" I'd want both of the functions to be able to use the same pointer to read from the same raw data memory, rather than first having to copy the raw data into distinct data structs, which will then immediately be transformed from the raw data into a PNG/DEP.

2023-08-02 14:29 UTC, bhaney commented on camera_realsense.cpp
> +    std::shared_ptr<DeviceProperties> device_;
device_ is a shared memory object that is shared between two parallel loops - one loop that runs the intel realsense code which pulls images from the intel realsense, and the second which is the persistent Camera object implemented by the C++ SDK and which interacts with gRPC. device stores a mutex and a bools which state whether the device is running. It's important that both the gRPC server, and the frameLoop know if the device ha stopped and needs to be restarted, and that things get restarted in the right order.

2023-08-02 14:31 UTC, bhaney commented on camera_realsense.cpp
> +        if (attrs->count("width_px") == 1) {
Nice, I think I will hold off for now and let that be a future improvement

2023-08-02 14:47 UTC, bhaney commented on camera_realsense.cpp
> +        std::tie(props, disableColor, disableDepth) = initialize(cfg);
nice, done

2023-08-02 14:50 UTC, bhaney commented on camera_realsense.cpp
> +                std::string endianString = (littleEndianDepth) ? "true" : "false";
done

2023-08-02 15:05 UTC, bhaney commented on camera_realsense.cpp
> +                    encodeColorRAWToResponse((const unsigned char*)latestColorFrame.get_data(),
I get a warning from the compiler when I use a void* rather than unsigned char*
```
camera_realsense.cpp: In function '{anonymous}::raw_camera_image {anonymous}::encodeColorRAW(const void*, uint32_t, uint32_t)':
camera_realsense.cpp:248:49: warning: pointer of type 'void *' used in arithmetic [-Wpointer-arith]
  248 |         std::memcpy(rawBuf.get() + offset, data + pixelOffset, 3);  // 3 bytes for RGB
```
So i think I'm going to keep this as a unsigned char* to avoid the warning.

2023-08-02 15:05 UTC, bhaney commented on camera_realsense.cpp
> +                    encodeColorPNGToResponse((const uint8_t*)latestColorFrame.get_data(),
changed it to void*

2023-08-02 15:28 UTC, bhaney commented on camera_realsense.cpp
> +        auto response =
changed the response to print an error and return an empty AttributeMap (as was done in point_cloud)

2023-08-02 15:48 UTC, bazile-clyde commented on camera_realsense.cpp
> +    std::shared_ptr<DeviceProperties> device_;
That makes sense. Thanks for the explanation.

2023-08-02 15:55 UTC, bazile-clyde approved these changes

2023-08-02 15:55 UTC, bazile-clyde commented on camera_realsense.cpp
> +    void reconfigure(vsdk::Dependencies deps, vsdk::ResourceConfig cfg) override {
Gotcha.

2023-08-02 16:27 UTC, merged