RSDK-4281: Shutting down viam-server causes intel realsense module to seg-fault if the component is currently running
viamrobotics/viam-camera-realsense pull request #27
Opened 2024-02-12 16:44 UTC by hexbabe

## Context for why this solution (probably) works

I built the module as a pure binary and tried repro-ing as per the ticket. Could not get it to repro after many attempts. Figured it might be an appimage issue. AppImages are still pretty black-box to me. Did the most sane thing 😂 and just bumped our dependency to it to a more recent version. Issue seems to be gone: tested on my RPI and Ubuntu setups

## Testing
Could someone also test on their machine(s) to verify?

[Download AppImage](https://drive.google.com/file/d/1gLZH0az6N7V_XZTTIshfsk5LtCfOhMim/view?usp=sharing)

2024-02-12 16:54 UTC, hexbabe commented on packaging/appimages/viam-camera-realsense-aarch64.yml
> +  comp: gzip
Required now by the bumped version of appimage-builder. Let me know if we should use a different compression method

2024-02-12 19:11 UTC, seanavery requested changes
Tested out appimage on RPI4 bullseye, unfortunately, it appears I am still getting segfault. Here are the logs:

```
2024-02-12T19:10:05.710Z   error robot_server   server/entrypoint.go:166   Fatal error running server, exiting now: error closing module manager: error while stopping module intel: signal: segmentation fault  
2024-02-12T19:10:05.709Z   error robot_server   server/entrypoint.go:186   error serving web   error error closing module manager: error while stopping module intel: signal: segmentation fault  
2024-02-12T19:10:05.608Z   info robot_server.process.intel_/home/viam/realsense-img.StdOut   pexec/managed_process.go:244   \_ [2024-02-12 14:10:05.608740] [0x0000007fa9f2d040] [info] Shutting down gracefully.  
2024-02-12T19:10:05.608Z   info robot_server.process.intel_/home/viam/realsense-img.StdOut   pexec/managed_process.go:244   \_ end of serve func  
2024-02-12T19:10:05.607Z   info robot_server.process.intel_/home/viam/realsense-img   pexec/managed_process_unix.go:91   stopping process 180603 with signal terminated  
2024-02-12T19:10:05.607Z   info robot_server.process.intel_/home/viam/realsense-img.StdOut   pexec/managed_process.go:244   \_ end of frameLoop function  
2024-02-12T19:10:05.606Z   info robot_server.process.intel_/home/viam/realsense-img.StdOut   pexec/managed_process.go:244   \_ end of frameLoop loop  
2024-02-12T19:10:05.606Z   info robot_server.process.intel_/home/viam/realsense-img.StdOut   pexec/managed_process.go:244   \_ [frameLoop] pipeline stopped, exiting frame loop  
2024-02-12T19:10:04.977Z   info robot_server.process.intel_/home/viam/realsense-img.StdOut   pexec/managed_process.go:244   \_ [frameLoop] start loop  
2024-02-12T19:10:04.801Z   info robot_server.process.intel_/home/viam/realsense-img.StdOut   pexec/managed_process.go:244   \_ [frameLoop] start loop  
2024-02-12T19:10:04.767Z   info robot_server   rpc/server.go:816   stopped cleanly 
```

2024-02-12 20:39 UTC, abe-winter reviewed
other people on this review understand appimage + realsense better than I do so will let them do signoff

from my perspective: no harm in bumping appimage builder even if it doesn't solve the problem. would prefer clearer repro case, but this is a thorny one

2024-02-12 21:03 UTC, hexbabe commented
> other people on this review understand appimage + realsense better than I do so will let them do signoff
> 
> from my perspective: no harm in bumping appimage builder even if it doesn't solve the problem. would prefer clearer repro case, but this is a thorny one

Yeah... @seanavery and I were investigating a little offline and upon trying to repro a second time on the same setup (RPI4 Bullseye), the segfault didn't happen. I tried the pure binary method to try to be able to find the exact cause of it, but seeing that the error only happens with AppImages, it makes it extremely difficult to do so using debuggers.

2024-02-12 22:26 UTC, hexbabe commented on src/camera_realsense.cpp
> +    std::this_thread::sleep_for(std::chrono::milliseconds(100));
I didn't want this to be part of the solution we implement, but it does get the job done. Not exactly sure why it prevents segfault

2024-02-13 14:49 UTC, hexbabe commented
Synced with Benji and we think a good course of action to take is to implement these bandaid fixes, but also hand off a minimal example of the segfault with a reduced version of the module to the SDK team, since the root of the segfault more than likely comes from our C++ SDK.

2024-02-13 15:35 UTC, seanavery approved these changes

2024-02-13 15:35 UTC, seanavery commented on src/camera_realsense.cpp
> +    std::this_thread::sleep_for(std::chrono::milliseconds(100));
@hexbabe Appimage seems to be working without segfault. Although as mentioned, it is hard to repro.

I am ok with adding timeout on deconstuctor. Would be good to add TODO comment here with Jira ticket linking to SDK investigation.

2024-02-13 16:49 UTC, bazile-clyde commented on src/camera_realsense.cpp
> +    std::this_thread::sleep_for(std::chrono::milliseconds(100));
> Not exactly sure why it prevents the segfault.
So generally, you do _not_ want to do this. We don't know if this solves the problem or makes the problem less likely to happen since we don't know what the root cause of the problem is. We could be setting ourselves up for failure by making this harder to reproduce. In C++, you don't actually call destructors explicitly. This could cause non-obvious 100ms delays in downstream functions. If you're wondering why this seems to fix the problem, you can see what happens just before and after this destructor is called, possibly by printing out a stack trace. _Something_ is using memory it's not supposed to. We'd want to find what that something is.

2024-02-13 17:10 UTC, hexbabe commented on src/camera_realsense.cpp
> +    std::this_thread::sleep_for(std::chrono::milliseconds(100));
> Synced with Benji and we think a good course of action to take is to implement these bandaid fixes, but also hand off a minimal example of the segfault with a reduced version of the module to the SDK team, since the root of the segfault more than likely comes from our C++ SDK.

@bazile-clyde would you suggest that we don't go push the timeout even as a temporary fix? I am working on a version of the module that will make it easy to repro

2024-02-13 17:18 UTC, bazile-clyde commented on src/camera_realsense.cpp
> +    std::this_thread::sleep_for(std::chrono::milliseconds(100));
Yes, I think it's better to wait for a more permanent, clear fix. This may introduce more complicated errors around object destruction.

2024-02-13 17:20 UTC, hexbabe commented on src/camera_realsense.cpp
> +    std::this_thread::sleep_for(std::chrono::milliseconds(100));
Okay that sounds good to me. I will continue making the reduced module and I think it's fine to bump the appimage-builder dependency.

2024-02-13 18:02 UTC, merged