Add github actions for docker and appimages
viamrobotics/viam-camera-realsense pull request #3
Opened 2023-08-04 19:00 UTC by bhaney

2023-08-04 20:11 UTC, bazile-clyde approved these changes
LGTM! Mostly deferring to James for the Docker stuff.

2023-08-07 17:39 UTC, Otterverse requested changes
Got quite a few issues here (sorry!), but all mostly small. Most are noted inline, but additionally, there are some issues not directly modified by this PR with the Dockerfile and the Makefile that concern me.

1. Why not use canon instead of custom docker run/copy commands? It'd make it more consistent with RDK and other repos that way, and simplify some target commands.
2. There's a docker run target in the makefile using CAP_SYSADMIN which effectively breaks docker's security, and isn't good practice. If you must run an appimage for testing inside a docker container, use APPIMAGE_EXTRACT_AND_RUN=1 as documented here: https://docs.appimage.org/user-guide/troubleshooting/fuse.html#extract-and-run-type-2-appimages
3. (minor) The dockerfile runs apt-get update multiple times, which is a bit wasteful.
4. (minor) The dockerfile also downloads appimage-builder from source, rather than just pinning a version with pip.
5. (question) Why does the dockerfile install things to $HOME/opt/src? I'd expect /opt/src or $HOME/src, but $HOME/opt/src feels like some conflation of the two.

2023-08-07 17:39 UTC, Otterverse commented on Makefile
> +	mkdir -p bin && \
Why recreate this directory here? It's unclear what it's used for. If something gets put here within the appimage recipe, then the recipe should probably be removing/recreating the directory.

2023-08-07 17:39 UTC, Otterverse commented on Makefile
> +	rm -rf bin | true && \
Single pipe | is going to pipe STDOUT to STDIN of the "true" command, not do an "or" like it seems you're expecting. Also, shouldn't be needed as the "f" option on rm forces and ignores missing files/folders anyway. (It always returns "success" with force enabled.)

2023-08-07 17:39 UTC, Otterverse commented on Makefile
> +	rm -rf deploy | true && \
Same as before, single pipe doesn't do what you think, but also isn't needed.

2023-08-07 17:39 UTC, Otterverse commented on Makefile
>  copy-bin:
Is there a reason to avoid using canon here? This entire target wouldn't be needed as the source folder would be mounted from the host in the first place.

2023-08-07 17:39 UTC, Otterverse commented on .github/workflows/docker.yml
> +            make_target: 'docker-cache-arm64-ci'
There's no reason to use a matrix when you only have one target.

2023-08-07 17:39 UTC, Otterverse commented on .github/workflows/main.yml
> +  docker:
What's the point in running this on every push? It should only rebuild if the dockerfile changes I think.

2023-08-07 17:39 UTC, Otterverse commented on .github/workflows/appimage.yml
> +            platform: linux/arm64
No purpose in "matrix" if there's only one entry.

2023-08-07 17:39 UTC, Otterverse commented on .github/workflows/appimage.yml
> +        sudo apt update
What's the purpose of this? No apt actions are taking place after this.

2023-08-07 17:39 UTC, Otterverse commented on .github/workflows/appimage.yml
> +          - arch: [arm64, qemu-host]
Why not use buildjet here? They're likely faster than our qemu emulated ones (which are going away at some point anyway.)

2023-08-07 20:01 UTC, bhaney commented
> Got quite a few issues here (sorry!), but all mostly small. Most are noted inline, but additionally, there are some issues not directly modified by this PR with the Dockerfile and the Makefile that concern me.

Mostly cargo-culted, and Frakensteined copy-pasted from previous Makefiles and Dockerfiles I have previously used until things compiled. Nice to learn more about how things actually work!

> 
>     1. Why not use canon instead of custom docker run/copy commands? It'd make it more consistent with RDK and other repos that way, and simplify some target commands.

canon for me didn't have the Viam C++ SDK, and also I was getting weird protobuf version errors when I installed the C++ SDK in canon (two different versions of protobuf shared libraries). Just decided to start with the C++ SDK dockerfile and build on top of that/add things until everything compiled. 

>     2. There's a docker run target in the makefile using CAP_SYSADMIN which effectively breaks docker's security, and isn't good practice. If you must run an appimage for testing inside a docker container, use APPIMAGE_EXTRACT_AND_RUN=1 as documented here: https://docs.appimage.org/user-guide/troubleshooting/fuse.html#extract-and-run-type-2-appimages

run-docker isn't used in github actions and was just for my own personal use for debugging compilation errors while building the module. I'll remove the target from the makefile.

>     3. (minor) The dockerfile runs apt-get update multiple times, which is a bit wasteful.

Sometimes you just want to make sure! I'll delete the extra ones and confirm everything still compiles all right. 

>     4. (minor) The dockerfile also downloads appimage-builder from source, rather than just pinning a version with pip.

Will change, copy/pasted from another Dockerfile 
> 
>     5. (question) Why does the dockerfile install things to $HOME/opt/src? I'd expect /opt/src or $HOME/src, but $HOME/opt/src feels like some conflation of the two.

Will change, copy/pasted from another Dockerfile . Though Docker here is just used to compile the binary and create the AppImage, and nothing more, so it seems like what the directory is called doesn't really matter.

2023-08-07 20:07 UTC, bhaney commented on Makefile
> +	docker push 'ghcr.io/viamrobotics/viam-camera-realsense:arm64-cache'
copy-paste from RDK workflow, it seems like in that repo there is only a canon-cache? I'm not sure of the difference between canon and  canon-cache. When using canon it only downloads canon-cache. I'll get rid of the "cache" string everywhere

2023-08-07 20:08 UTC, bhaney commented on Makefile
> +	rm -rf bin | true && \
copy/paste from another Makefile, will remove the second expression

2023-08-07 20:12 UTC, bhaney commented on Makefile
> +	rm -rf deploy | true && \
removed the latter expression

2023-08-07 20:15 UTC, bhaney commented on Makefile
>  copy-bin:
The canon RDK images didn't have the libraries I needed, so I just used classic Docker to build the app image and copy it out of the container

2023-08-07 20:17 UTC, bhaney commented on .github/workflows/appimage.yml
> +          - arch: [arm64, qemu-host]
will switch to buildjet

2023-08-07 21:26 UTC, bhaney commented on .github/workflows/appimage.yml
> +        sudo apt update
removed

2023-08-07 21:35 UTC, bhaney commented on .github/workflows/main.yml
> +  docker:
removed from this file, and added a on: push: method to the docker.yml file

2023-08-07 22:05 UTC, Otterverse commented
> canon for me didn't have the Viam C++ SDK, and also I was getting weird protobuf version errors when I installed the C++ SDK in canon (two different versions of protobuf shared libraries). Just decided to start with the C++ SDK dockerfile and build on top of that/add things until everything compiled.

Sorry, I wasn't clear there. I meant the "canon" CLI utility, not the pre-built images. I totally understand that you need to create your own docker image for this. I meant more the makefile "run-docker" target and stuff. It could just be "canon" if you set up a .canon.yaml here, and then it'd be trivial to drop into the container. Sounds like you're removing that anyway though, so irrelevant now I think.

2023-08-07 22:09 UTC, Otterverse commented on Makefile
> +	docker push 'ghcr.io/viamrobotics/viam-camera-realsense:arm64-cache'
Canon itself is built in the SysOps repo. The "-cache" version basically adds about 700MB of pre-downloaded go modules in ~/go/mod/ so that you (and the CI) don't have to download them all every time a container is spun up. So for RDK, there's never really a point for the non-cache use of canon. (But because it's built in two parts, updating the cache layer is far faster than rebuilding the whole image every time.)

2023-08-07 22:10 UTC, bhaney commented on .github/workflows/docker.yml
> +            make_target: 'docker-cache-arm64-ci'
changed away from matrix

2023-08-07 22:10 UTC, bhaney commented on .github/workflows/appimage.yml
> +            platform: linux/arm64
done

2023-08-07 22:11 UTC, Otterverse commented on Makefile
>  copy-bin:
As mentioned in the other comment, I meant use the "canon" cli utility to run your custom image. Then it handles all the magic of setup/teardown for you when you run locally, and stuff built in-place is already available outside the container with no need for extra copy commands and stuff.

2023-08-07 23:47 UTC, Otterverse requested changes
A another chunk of suggestions! Sorry I didn't catch some of these on the first pass. On the plus side, I tested building from this branch with canon and it _almost_ "just works" (there's one issue in our dockerfile that breaks things.)

2023-08-07 23:47 UTC, Otterverse commented on Makefile
This target ("build") should go away entirely, right? It's replaced by "docker-arm64" if I'm not mistaken.

2023-08-07 23:47 UTC, Otterverse commented on etc/Dockerfile.debian.bookworm
So the last steps in this file should be removed (I can't comment on those lines directly as they're not modified yet.) The viam-camera-realsense source code shouldn't live in the image, nor should it build the actual binary here when creating the image.

2023-08-07 23:47 UTC, Otterverse commented on Makefile
>  copy-bin:
This "copy-bin" target should go away entirely, as the docker image should no longer contain the actual source code for this repo (which will become out of date quickly.) Instead, you should add a .canon.yaml here configured to use the image you are building. Then all of what was in "copy-bin" simply becomes `canon -arch arm64 make package` and will use the exact source code the user is working with, rather than a potentially obsolete copy from when the image was built.

2023-08-07 23:47 UTC, Otterverse commented on Makefile
>  copy-bin:
For the .canon.yaml you should only need a couple lines.

```
viam-camera-realsense:
    arch: arm64
    image: ghcr.io/viamrobotics/viam-camera-realsense:arm64
    persistent: true
```

2023-08-07 23:47 UTC, Otterverse commented on Makefile
>  package:
This should depend on the "camera-module" target, otherwise it's going to package nothing.

2023-08-07 23:47 UTC, Otterverse commented on etc/Dockerfile.debian.bookworm
Also, near the top of the file, you set "ENV HOME /root" but the problem is that this persists to RUNTIME as well, not just buildtime. That means anything that tries to use another user (such as the canon utility) will fail, as it's home directory will be set to "/root" If you need a variable, us another variable name here. Or just hardcode "/root" in the few places you use it.

2023-08-07 23:47 UTC, Otterverse commented on Makefile
>  copy-bin:
Caveat... this ALMOST works. You have forced the ENV var "HOME" to be set in the dockerfile though, so canon is broken since the user it creates still has it's home directory forced to root (where it doesn't have permissions.)

2023-08-08 15:47 UTC, bhaney commented on .github/workflows/appimage.yml
> +    runs-on: [buildjet-2vcpu-ubuntu-2204-arm]
done -- switched to 8. Some compilation and `make install`s should be able to take advantage of more cpus

2023-08-08 15:48 UTC, bhaney commented on .github/workflows/appimage.yml
> +      uses: google-github-actions/auth@v0.4.3
done- mindless copy/paste

2023-08-08 15:48 UTC, bhaney commented on .github/workflows/appimage.yml
> +        headers: "Cache-Control: no-cache"
done

2023-08-08 15:48 UTC, bhaney commented on .github/workflows/docker.yml
> +            make_target: 'docker-arm64-ci'
done

2023-08-08 16:45 UTC, bhaney commented on Makefile
>  package:
done

2023-08-08 16:46 UTC, bhaney commented on etc/Dockerfile.debian.bookworm
removed the HOME ENV variable, and tested it out with canon - it works now!

2023-08-08 16:46 UTC, bhaney commented on Makefile
removed the build target

2023-08-08 17:57 UTC, bhaney commented on Makefile
>  copy-bin:
nicely works with canon now

2023-08-08 20:47 UTC, Otterverse approved these changes
LGTM! Nice work getting that docker image whipped into shape, and working with canon! Left a couple of (totally optional) notes about how you can reduce the image size, but up to you if you want to bother or not.

2023-08-08 20:47 UTC, Otterverse commented on etc/Dockerfile.debian.bookworm
> +RUN cd /root/opt/src && \
[nit/optional] This run command could end with `&& rm -rf /root/opt/src/librealsense` to make the image smaller. Each dockerfile command creates a layer, but if you pull in files, AND remove them in the same RUN command, then they don't persist in the layer. Only what was built and installed would remain, thus making the overall image smaller in size.

2023-08-08 20:47 UTC, Otterverse commented on etc/Dockerfile.debian.bookworm
> +RUN cd /root/opt/src && \
[opt] This too could end in `&& rm -rf ...`

2023-08-08 21:29 UTC, merged