RSDK-6737: Add note about librealsense Ubuntu-only requirement in README
viamrobotics/viam-camera-realsense pull request #30
Opened 2024-02-26 19:48 UTC by hexbabe

https://viam.atlassian.net/browse/RSDK-6737

2024-02-26 19:58 UTC, randhid approved these changes

2024-02-26 21:00 UTC, sguequierre requested changes

2024-02-26 21:00 UTC, sguequierre commented on README.md
> +This module depends on the [`librealsense` SDK](https://github.com/IntelRealSense/librealsense/releases). As of the time of writing, Ubuntu is the the only Linux Distro `librealsense` officially supp
```suggestion
This module depends on the [`librealsense` SDK](https://github.com/IntelRealSense/librealsense/releases). As of the time of writing, Ubuntu is the only Linux Distro `librealsense` officially supports. The module works on our setups using Bullseye on RPI4, and some setups on Bookworm. However, we recommend adhering to the requirements of the SDK dependency and to use Ubuntu when possible to avoid instability and unexpected behavior. 
```
"our setups" phrasing is a bit confusing to me-- you mean `viam-server` setups?

2024-02-26 21:00 UTC, sguequierre commented on README.md
> +## Linux Distribution Recommendation
```suggestion
## Linux distribution recommendation
```

2024-02-27 22:51 UTC, sguequierre approved these changes
LGTM!

2024-02-27 22:52 UTC, merged