[RSDK-6710] Consume depth map transcoders from C++ SDK
viamrobotics/viam-camera-realsense pull request #36
Opened 2024-04-15 18:46 UTC by hexbabe

2024-04-15 21:16 UTC, hexbabe commented on src/camera_realsense.cpp
> +        sdk::API::get<sdk::Camera>(), sdk::Model{kAPINamespace, kAPIType, kAPISubtype},
I didn't know that the repo had `make format` until today so I finally ran that lol. So these are just formatting changes please ignore

2024-04-15 21:17 UTC, hexbabe commented on src/camera_realsense.hpp
> +class CameraRealSense : public sdk::Camera, public sdk::Reconfigurable {
API changes in C++ SDK to account for

2024-04-16 16:08 UTC, randhid approved these changes

2024-04-16 17:36 UTC, seanavery approved these changes

2024-04-16 17:37 UTC, bhaney requested changes
Please do one more manual test: set the real sense config to little_endian true, and see if the depth image in the RC card gets all messed up as a result. That should be a visual confirmation that little_endian feature still works

2024-04-16 21:41 UTC, bhaney approved these changes
LGTM

2024-04-16 21:43 UTC, merged