Add PCD support and organize encoding helpers
viamrobotics/viam-camera-realsense pull request #41
Opened 2024-06-18 16:18 UTC by hexbabe

2024-06-18 16:20 UTC, hexbabe commented
```
6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [get_image] total: 14ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [GetImage] JPEG color encode: 14ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [get_image] total: 24ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [GetImage] JPEG color encode: 24ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [get_image] total: 10ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [GetImage] JPEG color encode: 10ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [get_image] total: 33ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [GetImage] JPEG color encode: 33ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [get_image] total: 10ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [GetImage] JPEG color encode: 10ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [frameLoop] wait for frames: 0ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [frameLoop] total: 680ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [frameLoop] frame alignment: 677ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [get_image] total: 11ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [GetImage] JPEG color encode: 11ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [get_point_cloud] total: 694ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [get_image] total: 14ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [GetImage] JPEG color encode: 14ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [get_image] total: 31ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [GetImage] JPEG color encode: 31ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [get_image] total: 11ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [GetImage] JPEG color encode: 11ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [frameLoop] wait for frames: 0ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [frameLoop] total: 639ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [frameLoop] frame alignment: 637ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [get_image] total: 18ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [GetImage] JPEG color encode: 18ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [get_image] total: 13ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [GetImage] JPEG color encode: 13ms

6/18/2024, 12:09:51 PM info robot_server.modmanager.process.irs-local-mod_/home/seanyu/viam-camera-realsense-latest-aarch64.AppImage.StdOut pexec/managed_process.go:282 \_ [get_image] total: 19ms
```
Since we put PCD processing in the `get_point_clouds` method instead of the frame loop. It shouldn't mess with the performance of get_image or the frame loop, but just in case I checked some of the debug spans and it looks 👍

2024-06-18 19:11 UTC, seanavery commented on src/encoding.hpp
> +std::vector<unsigned char> rsPointsToPCDBytes(const rs2::points& points, const rs2::frame& colorFrame) {
[q] Do you have any resources/examples or more info on how the pcd transformation is done here?

2024-06-18 19:21 UTC, seanavery reviewed
LGTM. 
Seems great to have pointclouds native to the module now!
- Makes sense that the `get_point_cloud` calls would not affect the performance of background image loop thread.
  - Looks like cpp sdk grpc stuff uses CompletionQueue async interface ([ref](https://grpc.io/docs/languages/cpp/async/)), so long response times here should not affect anything on the main thread either.
- Any info you have to help me grok `rsPointsToPCDBytes` helper addition would be awesome (Not up to speed yet with librealsense/pc formatting).

2024-06-18 21:17 UTC, bhaney requested changes
Thanks for the addition - we'll want to make sure that the points created by the function are actually scaled to real-world distances. Also the 4MB grpc message limit is just a default, it is not a real limit, you don't want to destroy data with no way of recovering it. Potentially could create a new optional config for scaling down point clouds, or telling the user to use a smaller resolution of image

2024-06-18 21:17 UTC, bhaney commented on src/encoding.hpp
> +std::vector<unsigned char> rsPointsToPCDBytes(const rs2::points& points, const rs2::frame& colorFrame) {
Is there any way to add a test to this function? Essentially create a fake rs2::points (with no colorFrame) and see if it correctly encodes to the colorless PCD you expect

2024-06-18 21:17 UTC, bhaney commented on src/camera_realsense.cpp
> +    pcdBytes = rsPointsToPCDBytes(points, latestColorFrame);
You will want to confirm that the distances that get_pointcloud gives you are actually in units of mm and correspond to correct distances in the real world

2024-06-18 21:31 UTC, bhaney commented on src/encoding.hpp
> +    }
https://viam.atlassian.net/browse/RSDK-6025

2024-06-19 00:49 UTC, randhid approved these changes
few minor nits but this looks good to me!

2024-06-20 13:36 UTC, hexbabe commented on src/camera_realsense.cpp
> +    pcdBytes = rsPointsToPCDBytes(points, latestColorFrame);
<img width="1162" alt="Screenshot 2024-06-20 at 9 35 00 AM" src="https://github.com/viamrobotics/viam-camera-realsense/assets/55464069/82931a59-2f79-408b-b095-70cf5f3069a5">
Got it. These distances are right. The parts of my chair are around 0.5m-0.8m from the camera right now.

2024-06-20 13:36 UTC, hexbabe commented on src/encoding.hpp
> +std::vector<unsigned char> rsPointsToPCDBytes(const rs2::points& points, const rs2::frame& colorFrame) {
I followed this resource https://pointclouds.org/documentation/tutorials/pcd_file_format.html

2024-06-20 14:09 UTC, hexbabe commented on src/encoding.hpp
> +    }
Done, commented and bumped. Looks like Ethan assigned it to himself as a todo

Question: "User specified" where user = us Viam developers though right. We configure (or don't, hence the default 4mb) limits on viam-server and C++ SDK. To my knowledge, we don't have a way where end users can change the size limit?

On board with removing subsampling though since aforementioned ticket was picked up

2024-06-20 14:19 UTC, hexbabe commented on src/encoding.hpp
> +        height = colorFrame.as<rs2::video_frame>().get_height();
Adding a check for 0. I think since width and height are ints they can't be nil

2024-06-20 14:20 UTC, hexbabe commented on src/encoding.hpp
> +        for (size_t i = 0; i < dataBytes.size(); i += subsampleRatio * pointSize) {
Going to remove subsampling logic

2024-06-20 14:27 UTC, hexbabe commented on src/encoding.hpp
> +    }
Removed and replaced with error log

2024-06-20 15:57 UTC, randhid commented on src/encoding.hpp
> +        height = colorFrame.as<rs2::video_frame>().get_height();
width and height can't be, but can the `video_frame()` object (or anything called to wrap it) be empty and error? assuming no from the rs2 library but good to check where your underlying library can fail when you're wrapping your logic on top of it.

2024-06-20 16:10 UTC, hexbabe commented on src/encoding.hpp
> +std::vector<unsigned char> rsPointsToPCDBytes(const rs2::points& points, const rs2::frame& colorFrame) {
[rs2::points doesn't expose a constructor](https://github.com/IntelRealSense/librealsense/blob/e1688cc318457f7dd57abcdbedd3398062db3009/src/points.h#L18). Would have to use Gmock, but having a hard time getting the dep in Docker and building it. I can keep going, but it may required a larger time window to implement than expected

Did manage to add an integration test though. Copied it to my pi and ran it. 
```
seanyu@sean-luxonis:~ $ ./realsense-integration-tests-latest-aarch64.AppImage -module "./viam-camera-realsense-latest-aarch64.AppImage"
VIAM REALSENSE MODULE INTEGRATION TESTS
Tests defined at https://github.com/viamrobotics/viam-camera-realsense/tree/main/integration/tests
checking if file exists at "./viam-camera-realsense-latest-aarch64.AppImage"
Starting the tests...
PASS
all tests succeeded!
```

2024-06-20 16:11 UTC, hexbabe commented on src/encoding.hpp
> +        height = colorFrame.as<rs2::video_frame>().get_height();
Added a dynamic pointer cast and checked for nil. Great point!

2024-06-20 16:52 UTC, randhid commented on src/encoding.hpp
> +std::vector<unsigned char> rsPointsToPCDBytes(const rs2::points& points, const rs2::frame& colorFrame) {
let's skip testing this for now.

2024-06-20 17:30 UTC, randhid commented on src/encoding.hpp
> +        height = colorFrame.as<rs2::video_frame>().get_height();
works for me!

2024-06-20 17:30 UTC, randhid approved these changes

2024-06-20 17:30 UTC, randhid commented on .gitignore
>  .vscode
```suggestion
.vscode

```

2024-06-20 19:22 UTC, seanavery approved these changes

2024-06-20 20:39 UTC, bhaney approved these changes
LGTM!

2024-06-21 15:40 UTC, merged