RSDK-8195   Set `supports_pcd` to true now in RealSense
viamrobotics/viam-camera-realsense pull request #48
Opened 2024-07-15 13:55 UTC by hexbabe

[RSDK-8195](https://viam.atlassian.net/browse/RSDK-8195)

Forgot to change properties after adding new pcd method

Tested with join-point-clouds module to [verify that we can invoke get_properties properly](https://github.com/viam-modules/join-point-clouds/blob/a473eac1b52801f34492936746017e00f2e140ac/src/main.cpp#L48)

2024-07-15 15:31 UTC, hexbabe commented
@bhaney since Rand is OOO

2024-07-15 20:34 UTC, bhaney requested changes
There is a config parameter in the realsense module called "enable_point_clouds" which would toggle on or off the `enablePointClouds ` bool. You should go through the code and remove the config parameter, as well as the enablePointClouds bool 


struct RealSenseProperties also has enablePointClouds bool as a field.

And please continue adding me to PRs for the intel realsense, even when Rand is around

2024-07-16 13:22 UTC, hexbabe commented
> There is a config parameter in the realsense module called "enable_point_clouds" which would toggle on or off the `enablePointClouds ` bool. You should go through the code and remove the config parameter, as well as the enablePointClouds bool
> 
> struct RealSenseProperties also has enablePointClouds bool as a field.
> 
> And please continue adding me to PRs for the intel realsense, even when Rand is around

Got it. I removed `enable_point_clouds` in config validation and traces of `enablePointClouds` from the hpp and cpp files

2024-07-16 13:26 UTC, randhid commented
> > There is a config parameter in the realsense module called "enable_point_clouds" which would toggle on or off the `enablePointClouds ` bool. You should go through the code and remove the config parameter, as well as the enablePointClouds bool
> > struct RealSenseProperties also has enablePointClouds bool as a field.
> > And please continue adding me to PRs for the intel realsense, even when Rand is around
> 
> Got it. I removed `enable_point_clouds` in config validation and traces of `enablePointClouds` from the hpp and cpp files

Justy FYI - removing configuration attributes of a model is a breaking change.

I do not think we're at enough use of this mode to warrant a migration, but for something like webcam or transform camera I would have insisted we investigate usage and run a migration script to remove the attribute.

But for here - please update the attribute in the readme if it exists.

2024-07-16 13:28 UTC, hexbabe commented
> > > There is a config parameter in the realsense module called "enable_point_clouds" which would toggle on or off the `enablePointClouds ` bool. You should go through the code and remove the config parameter, as well as the enablePointClouds bool
> > > struct RealSenseProperties also has enablePointClouds bool as a field.
> > > And please continue adding me to PRs for the intel realsense, even when Rand is around
> > 
> > 
> > Got it. I removed `enable_point_clouds` in config validation and traces of `enablePointClouds` from the hpp and cpp files
> 
> Justy FYI - removing configuration attributes of a model is a breaking change.
> 
> I do not think we're at enough use of this mode to warrant a migration, but for something like webcam or transform camera I would have insisted we investigate usage and run a migration script to remove the attribute.
> 
> But for here - please update the attribute in the readme if it exists.

I don't think this attribute is documented

2024-07-16 13:29 UTC, randhid commented
> > > > There is a config parameter in the realsense module called "enable_point_clouds" which would toggle on or off the `enablePointClouds ` bool. You should go through the code and remove the config parameter, as well as the enablePointClouds bool
> > > > struct RealSenseProperties also has enablePointClouds bool as a field.
> > > > And please continue adding me to PRs for the intel realsense, even when Rand is around
> > > 
> > > 
> > > Got it. I removed `enable_point_clouds` in config validation and traces of `enablePointClouds` from the hpp and cpp files
> > 
> > 
> > Justy FYI - removing configuration attributes of a model is a breaking change.
> > I do not think we're at enough use of this mode to warrant a migration, but for something like webcam or transform camera I would have insisted we investigate usage and run a migration script to remove the attribute.
> > But for here - please update the attribute in the readme if it exists.
> 
> I don't think this attribute is documented in the readme or in docs

perfect

2024-07-16 16:09 UTC, bhaney approved these changes
LGTM

2024-07-16 17:03 UTC, merged