RSDK-5239, RSDK-5388: use CMake and CTest
viamrobotics/viam-camera-realsense pull request #9
Opened 2023-10-18 18:51 UTC by bhaney

Tested out on orin nano and raspberry pi: still works!

This PR does NOT add any real tests, but simply changes the compilation structure for the module. The meat of tests will come in the next PR.

This PR includes:

- changes the directory structure of the intel realsense module, adding a src and test directory
- creates a header file for the intel realsense
- introduces the use of CMake for compilation
- introduces a github action for testing using CTest
- changes the dockerfile slightly to install GTest, as well as create a new Dockerfile for cuda (future work)

2023-10-19 15:47 UTC, bhaney commented on tests/camera_realsense_test.cpp
> +TEST(ResourceTest, Type) {
Just a small, silly test to make sure the CI is working properly. The actual tests will be in the next PR

2023-10-19 17:43 UTC, acmorrow requested changes
Looks good, lots of little small things and improvements, but nothing super important. I do note one future consideration about how testing will work.

2023-10-19 17:43 UTC, acmorrow commented on tests/camera_realsense_test.cpp
> +int main(int argc, char **argv) {
It looks like you link `GTest::main` above, in which case you probably don't need to declare your own mainline. Or, if you really do want your own main, you can do without linking `GTest::main`.

2023-10-19 17:43 UTC, acmorrow commented on tests/camera_realsense_test.cpp
> +TEST(ResourceTest, Type) {
I see a potential problem on the horizon. Currently, all the realsense stuff is compiled into an executable. If you want this test to be able to use it, it'll need to be in some sort of library.

2023-10-19 17:43 UTC, acmorrow commented on tests/CMakeLists.txt
> +find_package(viam-cpp-sdk REQUIRED)
You already did `find_package(viam-cpp-sdk REQUIRED)` in the parent CMakeLists so you probably don't need to say it here too.

2023-10-19 17:43 UTC, acmorrow commented on src/camera_realsense.hpp
> +namespace vsdk = ::viam::sdk;
If you follow my above suggestion, then I think you can remove this and just say `sdk::`

2023-10-19 17:43 UTC, acmorrow commented on CMakeLists.txt
> +    protobuf
Does `viam-camera-realsense` make direct use of `grpc++` and `protobuf`? If not, you can probably drop them. They will likely get automatically re-added because they are `PUBLIC` library dependencies of `viam-cpp-sdk::viamsdk`.

2023-10-19 17:43 UTC, acmorrow commented on CMakeLists.txt
> +find_package(viam-cpp-sdk REQUIRED)
I'd probably move this up above declaring the targets, maybe to around line 9.

2023-10-19 17:43 UTC, acmorrow commented on CMakeLists.txt
> +find_package(realsense2 REQUIRED)
I'd also move this up next to the other `find_package` call.

2023-10-19 17:43 UTC, acmorrow commented on CMakeLists.txt
> +    -O4
As far as I know, GCC only applies meaning to `-O3` and higher values are just reduced to that. And I'd rarely recommend `-O3` anyway: it can lead to larger code which is actually slower. Consider `-O2`.

2023-10-19 17:43 UTC, acmorrow commented on CMakeLists.txt
> +    -pthread
A better way to get the `-pthread` flag is to use the CMake pseudo-library `Threads::Thread`: https://github.com/viamrobotics/viam-cpp-sdk/blob/main/CMakeLists.txt#L211-L213

2023-10-19 17:43 UTC, acmorrow commented on CMakeLists.txt
> +    -Wl,-ldl
CMake has an abstraction for this:
- https://cmake.org/cmake/help/latest/variable/CMAKE_DL_LIBS.html.
- https://github.com/viamrobotics/viam-mlmodelservice-triton/blob/main/src/CMakeLists.txt#L54

2023-10-19 17:43 UTC, acmorrow commented on CMakeLists.txt
> +add_subdirectory(tests)
I'd move this down to the bottom after declaring your targets.

2023-10-19 17:43 UTC, acmorrow commented on Makefile
> +	make && \
Same thought that this is going to get you a serial build by default.

2023-10-19 22:49 UTC, bazile-clyde approved these changes
This looks great to me! The README updates making things really clear too. LGTM once Andrew's comments are addressed.

2023-10-19 22:49 UTC, bazile-clyde commented on Makefile
>  # compile the binary
Is that comment stale now? It doesn't look like it goes with `format` below.

2023-10-19 22:49 UTC, bazile-clyde commented on Makefile
> +	clang-format -i --style="{BasedOnStyle: Google, IndentWidth: 4, ColumnLimit: 100}" src/*.hpp
[opt] If you want to do this in one line, you can do...
```
$ ls src/*.{cpp,hpp}
src/camera_realsense.cpp  src/camera_realsense.hpp
```
or...
```
$ ls src/*.cpp src/*.hpp 
src/camera_realsense.cpp  src/camera_realsense.hpp
```

2023-10-20 15:44 UTC, bhaney commented on tests/camera_realsense_test.cpp
> +TEST(ResourceTest, Type) {
This is such a good point, because I could see situations where we would like to run tests on a real intel realsense (maybe to see if the hardware acts as expected) vs. a mock or simulated data stream (for the CI tests on github). Yes, making the tests into a library, and then creating two separate binaries (one for an actual realsense, one for a fake realsense in the CI) would be great

2023-10-20 18:44 UTC, bhaney commented on tests/camera_realsense_test.cpp
> +TEST(ResourceTest, Type) {
While this is a good idea, I think I'll wait until the next PR to implement, or else it will make this one a bit big

2023-10-20 18:47 UTC, bhaney commented on tests/camera_realsense_test.cpp
> +int main(int argc, char **argv) {
got Rid of the link to GTest::Main

2023-10-20 18:48 UTC, bhaney commented on tests/CMakeLists.txt
> +find_package(viam-cpp-sdk REQUIRED)
removed

2023-10-20 18:48 UTC, bhaney commented on src/camera_realsense.hpp
> +namespace realsense {
done, created viam::realsense

2023-10-20 18:48 UTC, bhaney commented on src/camera_realsense.hpp
> +constexpr char kResourceType[] = "CameraRealSense";
done

2023-10-20 18:48 UTC, bhaney commented on CMakeLists.txt
> +    -pthread
done

2023-10-20 18:49 UTC, bhaney commented on CMakeLists.txt
> +    -O4
done

2023-10-20 18:49 UTC, bhaney commented on CMakeLists.txt
> +    -Wl,-ldl
done

2023-10-20 18:49 UTC, bhaney commented on Makefile
> +	make && \
switched to using Ninja

2023-10-20 18:51 UTC, bhaney commented on CMakeLists.txt
> +add_subdirectory(tests)
done, moved to the bottom of the CMakeLists

2023-10-20 18:51 UTC, bhaney commented on src/camera_realsense.hpp
> +namespace vsdk = ::viam::sdk;
done

2023-10-20 18:51 UTC, bhaney commented on .github/workflows/test.yml
> +        run: make
switched to Ninja

2023-10-20 18:51 UTC, bhaney commented on CMakeLists.txt
> +    protobuf
removed - you were right

2023-10-20 18:52 UTC, bhaney commented on CMakeLists.txt
> +find_package(viam-cpp-sdk REQUIRED)
done

2023-10-20 18:52 UTC, bhaney commented on CMakeLists.txt
> +find_package(realsense2 REQUIRED)
done

2023-10-20 18:52 UTC, bhaney commented on Makefile
> +	clang-format -i --style="{BasedOnStyle: Google, IndentWidth: 4, ColumnLimit: 100}" src/*.hpp
nice suggestion, implemented

2023-10-20 18:55 UTC, bhaney commented on Makefile
>  # compile the binary
changed

2023-10-20 19:33 UTC, acmorrow commented on tests/camera_realsense_test.cpp
> +TEST(ResourceTest, Type) {
Yeah, that makes sense to me.

2023-10-20 19:36 UTC, acmorrow approved these changes
LGTM!

2023-10-20 19:58 UTC, merged